#db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/team_b
    username: team_b
    password: green502


mybatis:
  type-aliases-package: com.green.boardver2.model
  mapper-locations: mapper/**/*.xml

#swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: /download/

